format_version: 10
pipelines:
  mysql:
    group: App-Deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a66247d:
        git: https://github.com/agdevops01/expense-ansible-roles
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:+Dry2jMBtJyn+nVVJK0zRA==:Yb4u6zAd/sRstr7+LsO+Xw=="
    environment_variables:
      component: mysql
    template: ansible-app-deployment
